<?php
$shortcode_form = '<div class="whatapp-wrapper">';
$shortcode_form .= '<form class="whatapp-form" id="whatapp-form">';
$shortcode_form .= '<h3 class="whatapp-title">' . get_option( 'wp-phone-message-title' ) . '</h3>';
$shortcode_form .= '<p class="whatapp-text">' . get_option( 'wp-phone-message-text' ) . '</p>';

if ( get_option( 'wp-phone-message-name-active' ) ) {
	$shortcode_form .= '<input type="text" class="wp-phone-message-name" id="wp-phone-message-name" placeholder="' . get_option( 'wp-phone-message-name' ) . '"  ' . get_option( 'wp-phone-message-name-mandatory' ) . ' />';
}
if ( get_option( 'wp-phone-message-address-active' ) ) {
	$shortcode_form .= '<input type="text" class="wp-phone-message-address" id="wp-phone-message-address" placeholder="' . get_option( 'wp-phone-message-address' ) . '"  ' . get_option( 'wp-phone-message-address-mandatory' ) . ' />';
}
if ( get_option( 'wp-phone-message-phone-active' ) ) {
	$shortcode_form .= '<input type="text" class="wp-phone-message-phone" id="wp-phone-message-phone" placeholder="' . get_option( 'wp-phone-message-phone' ) . '"  ' . get_option( 'wp-phone-message-phone-mandatory' ) . ' />';
}
if ( get_option( 'wp-phone-message-email-active' ) ) {
	$shortcode_form .= '<input type="email" class="wp-phone-message-email" id="wp-phone-message-email" placeholder="' . get_option( 'wp-phone-message-email' ) . '"  ' . get_option( 'wp-phone-message-email-mandatory' ) . ' />';
}


// custom code for adding time picker in wp phone message
// the date today/tomrrow comes from the ACF field of each restaurant

$days = get_field( 'avui_dema' );
if ( ! empty( $days ) ) { // do only if there are days (today or tomorrow) checked in backend.

	ob_start();

	?>

    <div class="timepicker" data-post="<?php the_ID(); ?>"
         data-datepicker-nonce="<?php echo wp_create_nonce( 'get_hrs' ); ?>">

        <select class="timepicker__day" name="timepicker__day" id="timepicker__day">
            <option value="">Dia</option>

            <!-- option will be dynamically generated by the value of each restaurant in the backend -->
			<?php
			if ( in_array( 'Avui', $days ) ) {
				$avui = 'Avui (' . date( 'd/m' ) . ')';
				?>
                <option value="avui"><?php echo $avui; ?></option>
			<?php } ?>

			<?php
			if ( in_array( 'Demà', $days ) ) {
				$dema = 'Demà (' . date( 'd/m', strtotime( '+1 day' ) ) . ')';
				?>
                <option value="dema"><?php echo $dema; ?></option>
			<?php } ?>

        </select>

        <select class="timepicker__time" name="timepicker__time" id="timepicker__time">
            <option value="">Hora</option>
        </select>

    </div>

    <style>

        .timepicker {
            margin-top: 10px;
            display: flex;
            align-items: center;
        }

        .timepicker select {
            border-radius: 4px;
            flex-grow: 1;
            font-size: 15px;
            background: #fff;
            max-width: 50%;
        }

        .timepicker .timepicker__time {
            margin-left: 8px;
        }

    </style>


    <script>
        jQuery(document).ready(function ($) {

            $('select.timepicker__day').change(function () {

                var nonce = $('.timepicker').attr('data-datepicker-nonce');
                var selected = $('#timepicker__day').val();
                var post = $('.timepicker').attr('data-post');
                if ("" == selected) {
                    alert('Please select day.');
                    return false;
                }

                // do ajax request to get the time
                $.ajax({
                    method: "POST",
                    url: wp_phone_message_obj.ajax_url,
                    dataType: 'json',
                    data: {
                        action: 'get_hrs',
                        post_id: post,
                        day: selected,
                        nonce: nonce,
                    },
                    success: function (response) {

                        if (response.success) { // case: no errors

                            $('#timepicker__time').empty().append( response.options )

                        } else { // handle errors
                            alert(response.msg);
                        }
                    }

                });
            });
        });
    </script>

	<?php
	$shortcode_form .= ob_get_clean();
} else {
	$shortcode_form .= '<p style="color: #d61111; margin-bottom: 0;"> No hi ha opció </p>';
}


$shortcode_form .= '<textarea class="wp-phone-message-message" id="wp-phone-message-message" placeholder="' . get_option( 'wp-phone-message-textarea' ) . '" required ></textarea>';
$shortcode_form .= '<p class="whatapp-error" id="whatapp-error" ></p>';
$shortcode_form .= '<input hidden="text" id="wp-phone-message-full-phone-number" value="' . get_option( 'wp-phone-message-full-phone-number' ) . '" />';
$shortcode_form .= '<input type="submit" class="wp-phone-message-button" id="wp-phone-message-button" value="' . get_option( 'wp-phone-message-button' ) . '" />';
$shortcode_form .= '</form>';
$shortcode_form .= '</div>';
